#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check for .test.js, .test.ts, and .test.tsx files
if [ -n "$(git ls-files 'src/**/*.test.{js,ts,tsx}')" ]; then
  npm test
else
  echo "No test files found, skipping tests."
fi